server:
  port: 8817
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  data:
    solr:
      host: http://127.0.0.1:8080/solr
  datasource:
    username: root
    password: root
    url: 'jdbc:mysql://localhost:3306/pinyougoudb_shopping?useUnicode=true&characterEncoding=UTF-8'
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: 'shopping-search-ms'
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: true 
      max-connections: 50
      expiry-timeout: 10000
      idle-timeout: 30000

 